trigger:
    branches:
        include:
            - main

pool:
    vmImage: ubuntu-latest

steps:
    - task: Bash@3
      inputs:
          targetType: "inline"
          script: "env | sort"

    - task: Npm@1
      inputs:
          command: "install"
      displayName: "npm install"

    - task: Npm@1
      env:
          cypress_clientSecret: "$(cypress_clientSecret)"
          cypress_password: "$(cypress_password)"

      inputs:
          command: "custom"
          customCommand: "run cy:run"
      displayName: "cypress run tests"

    - task: Npm@1
      inputs:
          command: "custom"
          customCommand: "run cy:report"
      displayName: "generate cypress html report"

    - task: PublishBuildArtifacts@1
      inputs:
          PathtoPublish: "report"
          ArtifactName: "report"
          publishLocation: "Container"
